	git rm    JNI_call_study/JNI_call_study.sln
	git rm    JNI_call_study/JNI_call_study/AndroidManifest.xml
	git rm    JNI_call_study/JNI_call_study/JNI_call_study.vcxproj
	git rm    JNI_call_study/JNI_call_study/JNI_call_study.vcxproj.filters
	git rm    JNI_call_study/JNI_call_study/JNI_call_study.vcxproj.user
	git rm    JNI_call_study/JNI_call_study/Tegra-Android/Debug/JNI_call_study.log
	git rm    JNI_call_study/JNI_call_study/Tegra-Android/Debug/JNI_call_study.o
	git rm    JNI_call_study/JNI_call_study/Tegra-Android/Debug/JNI_call_study.tlog/JNI_call_study.lastbuildstate
	git rm    JNI_call_study/JNI_call_study/Tegra-Android/Debug/JNI_call_study.tlog/clang++-ld.bfd.read.1.tlog
	git rm    JNI_call_study/JNI_call_study/Tegra-Android/Debug/JNI_call_study.tlog/clang++-ld.bfd.write.1.tlog
	git rm    JNI_call_study/JNI_call_study/Tegra-Android/Debug/JNI_call_study.tlog/clang++-link.command.1.tlog
	git rm    JNI_call_study/JNI_call_study/Tegra-Android/Debug/JNI_call_study.tlog/clang++.compile.command.1.tlog
	git rm    JNI_call_study/JNI_call_study/Tegra-Android/Debug/JNI_call_study.tlog/clang++.compile.read.1.tlog
	git rm    JNI_call_study/JNI_call_study/Tegra-Android/Debug/JNI_call_study.tlog/clang++.compile.write.1.tlog
	git rm    JNI_call_study/JNI_call_study/Tegra-Android/Debug/JNI_call_study.tlog/clang++.read.1.tlog
	git rm    JNI_call_study/JNI_call_study/Tegra-Android/Debug/build/Gradle.config.cache
	git rm    JNI_call_study/JNI_call_study/Tegra-Android/Debug/build/build/android-profile/profile-2018-09-18-01-39-42-939.rawproto
	git rm    JNI_call_study/JNI_call_study/Tegra-Android/Debug/build/build/generated/source/r/debug/aa/bb/cc/R.java
	git rm    JNI_call_study/JNI_call_study/Tegra-Android/Debug/build/build/intermediates/blame/res/debug/multi/values.json
	git rm    JNI_call_study/JNI_call_study/Tegra-Android/Debug/build/build/intermediates/classes/debug/aa/bb/cc/BuildConfig.class
	git rm    JNI_call_study/JNI_call_study/Tegra-Android/Debug/build/build/intermediates/classes/debug/aa/bb/cc/JNI_call_study$1$1.class
	git rm    JNI_call_study/JNI_call_study/Tegra-Android/Debug/build/build/intermediates/classes/debug/aa/bb/cc/JNI_call_study$1$2.class
	git rm    JNI_call_study/JNI_call_study/Tegra-Android/Debug/build/build/intermediates/classes/debug/aa/bb/cc/JNI_call_study$1.class
	git rm    JNI_call_study/JNI_call_study/Tegra-Android/Debug/build/build/intermediates/classes/debug/aa/bb/cc/JNI_call_study.class
	git rm    JNI_call_study/JNI_call_study/Tegra-Android/Debug/build/build/intermediates/classes/debug/aa/bb/cc/R$attr.class
	git rm    JNI_call_study/JNI_call_study/Tegra-Android/Debug/build/build/intermediates/classes/debug/aa/bb/cc/R$string.class
	git rm    JNI_call_study/JNI_call_study/Tegra-Android/Debug/build/build/intermediates/classes/debug/aa/bb/cc/R.class
	git rm    JNI_call_study/JNI_call_study/Tegra-Android/Debug/build/build/intermediates/incremental-safeguard/debug/tag.txt
	git rm    JNI_call_study/JNI_call_study/Tegra-Android/Debug/build/build/intermediates/incremental/compileDebugAidl/dependency.store
	git rm    JNI_call_study/JNI_call_study/Tegra-Android/Debug/build/build/intermediates/incremental/mergeDebugAssets/merger.xml
	git rm    JNI_call_study/JNI_call_study/Tegra-Android/Debug/build/build/intermediates/incremental/mergeDebugJniLibFolders/merger.xml
	git rm    JNI_call_study/JNI_call_study/Tegra-Android/Debug/build/build/intermediates/incremental/mergeDebugResources/compile-file-map.properties
	git rm    JNI_call_study/JNI_call_study/Tegra-Android/Debug/build/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml
	git rm    JNI_call_study/JNI_call_study/Tegra-Android/Debug/build/build/intermediates/incremental/mergeDebugResources/merger.xml
	git rm    JNI_call_study/JNI_call_study/Tegra-Android/Debug/build/build/intermediates/incremental/mergeDebugShaders/merger.xml
	git rm    JNI_call_study/JNI_call_study/Tegra-Android/Debug/build/build/intermediates/incremental/packageDebug/dex-renamer-state.txt
	git rm    JNI_call_study/JNI_call_study/Tegra-Android/Debug/build/build/intermediates/incremental/packageDebug/file-input-save-data.txt
	git rm    JNI_call_study/JNI_call_study/Tegra-Android/Debug/build/build/intermediates/incremental/packageDebug/zip-cache/O2iSoWtAmhEgWE+286ScOQS57h8=
	git rm    JNI_call_study/JNI_call_study/Tegra-Android/Debug/build/build/intermediates/jniLibs/debug/armeabi-v7a/gdbserver
	git rm    JNI_call_study/JNI_call_study/Tegra-Android/Debug/build/build/intermediates/jniLibs/debug/armeabi-v7a/libJNI_call_study.so
	git rm    JNI_call_study/JNI_call_study/Tegra-Android/Debug/build/build/intermediates/jniLibs/debug/armeabi-v7a/libc++_shared.so
	git rm    JNI_call_study/JNI_call_study/Tegra-Android/Debug/build/build/intermediates/manifests/full/debug/AndroidManifest.xml
	git rm    JNI_call_study/JNI_call_study/Tegra-Android/Debug/build/build/intermediates/res/merged/debug/values/values.xml
	git rm    JNI_call_study/JNI_call_study/Tegra-Android/Debug/build/build/intermediates/res/resources-debug.ap_
	git rm    JNI_call_study/JNI_call_study/Tegra-Android/Debug/build/build/outputs/logs/manifest-merger-debug-report.txt
	git rm    JNI_call_study/JNI_call_study/Tegra-Android/Debug/build/generated/source/buildConfig/debug/aa/bb/cc/BuildConfig.java
	git rm    JNI_call_study/JNI_call_study/Tegra-Android/Debug/build/intermediates/transforms/dex/debug/folders/1000/1f/main/classes.dex
	git rm    JNI_call_study/JNI_call_study/Tegra-Android/Debug/build/intermediates/transforms/mergeJniLibs/debug/folders/2000/1f/main/lib/armeabi-v7a/gdbserver
	git rm    JNI_call_study/JNI_call_study/Tegra-Android/Debug/build/intermediates/transforms/mergeJniLibs/debug/folders/2000/1f/main/lib/armeabi-v7a/libJNI_call_study.so
	git rm    JNI_call_study/JNI_call_study/Tegra-Android/Debug/build/intermediates/transforms/mergeJniLibs/debug/folders/2000/1f/main/lib/armeabi-v7a/libc++_shared.so
	git rm    JNI_call_study/JNI_call_study/Tegra-Android/Debug/build/libs/armeabi-v7a/gdbserver
	git rm    JNI_call_study/JNI_call_study/Tegra-Android/Debug/build/libs/armeabi-v7a/libJNI_call_study.so
	git rm    JNI_call_study/JNI_call_study/Tegra-Android/Debug/build/libs/armeabi-v7a/libc++_shared.so
	git rm    JNI_call_study/JNI_call_study/Tegra-Android/Debug/build/nsight_tegra_build.gradle
	git rm    JNI_call_study/JNI_call_study/Tegra-Android/Debug/build/nsight_tegra_build_properties.gradle
	git rm    JNI_call_study/JNI_call_study/Tegra-Android/Debug/build/nsight_tegra_manifest.xml
	git rm    JNI_call_study/JNI_call_study/Tegra-Android/Debug/build/outputs/apk/JNI_call_study-debug.apk
	git rm    JNI_call_study/JNI_call_study/Tegra-Android/Debug/gradle.command.1.tlog
	git rm    JNI_call_study/JNI_call_study/Tegra-Android/Debug/gradle.write.1.tlog
	git rm    JNI_call_study/JNI_call_study/Tegra-Android/Debug/gradle_cache/4.1/fileChanges/last-build.bin
	git rm    JNI_call_study/JNI_call_study/Tegra-Android/Debug/gradle_cache/4.1/fileContent/fileContent.lock
	git rm    JNI_call_study/JNI_call_study/Tegra-Android/Debug/gradle_cache/4.1/fileHashes/fileHashes.bin
	git rm    JNI_call_study/JNI_call_study/Tegra-Android/Debug/gradle_cache/4.1/fileHashes/fileHashes.lock
	git rm    JNI_call_study/JNI_call_study/Tegra-Android/Debug/gradle_cache/4.1/javaCompile/classAnalysis.bin
	git rm    JNI_call_study/JNI_call_study/Tegra-Android/Debug/gradle_cache/4.1/javaCompile/javaCompile.lock
	git rm    JNI_call_study/JNI_call_study/Tegra-Android/Debug/gradle_cache/4.1/javaCompile/taskHistory.bin
	git rm    JNI_call_study/JNI_call_study/Tegra-Android/Debug/gradle_cache/4.1/javaCompile/taskJars.bin
	git rm    JNI_call_study/JNI_call_study/Tegra-Android/Debug/gradle_cache/4.1/taskHistory/fileSnapshots.bin
	git rm    JNI_call_study/JNI_call_study/Tegra-Android/Debug/gradle_cache/4.1/taskHistory/taskHistory.bin
	git rm    JNI_call_study/JNI_call_study/Tegra-Android/Debug/gradle_cache/4.1/taskHistory/taskHistory.lock
	git rm    JNI_call_study/JNI_call_study/Tegra-Android/Debug/gradle_cache/buildOutputCleanup/built.bin
	git rm    JNI_call_study/JNI_call_study/Tegra-Android/Debug/gradle_cache/buildOutputCleanup/cache.properties
	git rm    JNI_call_study/JNI_call_study/Tegra-Android/Debug/gradle_cache/buildOutputCleanup/cache.properties.lock
	git rm    JNI_call_study/JNI_call_study/jni/JNI_call_study.cpp
	git rm    JNI_call_study/JNI_call_study/res/values/strings.xml
	git rm    JNI_call_study/JNI_call_study/src/aa/bb/cc/JNI_call_study.java
	git rm    JNI_call_study/Tegra-Android/Debug/JNI_call_study.apk
	git rm    JNI_call_study/Tegra-Android/Debug/libJNI_call_study.so
	git rm    JNI_call_study/Tegra-Android/Debug/stripped_libJNI_call_study.so
	git rm    JNI_call_study/study/JNI_call_study.o
	git rm    JNI_call_study/study/JNI_call_study.o.readelf-a
